# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'searchPhotoDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_searchPhotoDialog(object):
    def setupUi(self, searchPhotoDialog):
        searchPhotoDialog.setObjectName(_fromUtf8("searchPhotoDialog"))
        searchPhotoDialog.resize(923, 649)
        self.buttonBox = QtGui.QDialogButtonBox(searchPhotoDialog)
        self.buttonBox.setGeometry(QtCore.QRect(570, 10, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.listPhotos = QtGui.QListWidget(searchPhotoDialog)
        self.listPhotos.setGeometry(QtCore.QRect(20, 10, 321, 291))
        self.listPhotos.setObjectName(_fromUtf8("listPhotos"))
        self.groupBoxCategory = QtGui.QGroupBox(searchPhotoDialog)
        self.groupBoxCategory.setGeometry(QtCore.QRect(360, 90, 331, 111))
        self.groupBoxCategory.setObjectName(_fromUtf8("groupBoxCategory"))
        self.radioPersona = QtGui.QRadioButton(self.groupBoxCategory)
        self.radioPersona.setGeometry(QtCore.QRect(10, 20, 116, 22))
        self.radioPersona.setObjectName(_fromUtf8("radioPersona"))
        self.radioLloc = QtGui.QRadioButton(self.groupBoxCategory)
        self.radioLloc.setGeometry(QtCore.QRect(110, 20, 116, 22))
        self.radioLloc.setObjectName(_fromUtf8("radioLloc"))
        self.radioButton = QtGui.QRadioButton(self.groupBoxCategory)
        self.radioButton.setGeometry(QtCore.QRect(200, 20, 116, 22))
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.MetadataLabel = QtGui.QLabel(self.groupBoxCategory)
        self.MetadataLabel.setGeometry(QtCore.QRect(10, 60, 66, 17))
        self.MetadataLabel.setObjectName(_fromUtf8("MetadataLabel"))
        self.lineMetadata = QtGui.QLineEdit(self.groupBoxCategory)
        self.lineMetadata.setGeometry(QtCore.QRect(80, 50, 201, 27))
        self.lineMetadata.setObjectName(_fromUtf8("lineMetadata"))
        self.CercaMetadataBtn = QtGui.QPushButton(self.groupBoxCategory)
        self.CercaMetadataBtn.setGeometry(QtCore.QRect(110, 80, 98, 27))
        self.CercaMetadataBtn.setObjectName(_fromUtf8("CercaMetadataBtn"))
        self.groupBoxFoto = QtGui.QGroupBox(searchPhotoDialog)
        self.groupBoxFoto.setGeometry(QtCore.QRect(360, 220, 321, 91))
        self.groupBoxFoto.setObjectName(_fromUtf8("groupBoxFoto"))
        self.labelTitol = QtGui.QLabel(self.groupBoxFoto)
        self.labelTitol.setGeometry(QtCore.QRect(10, 30, 66, 17))
        self.labelTitol.setObjectName(_fromUtf8("labelTitol"))
        self.lineTitol = QtGui.QLineEdit(self.groupBoxFoto)
        self.lineTitol.setGeometry(QtCore.QRect(80, 20, 201, 27))
        self.lineTitol.setObjectName(_fromUtf8("lineTitol"))
        self.cercaFotoBtn = QtGui.QPushButton(self.groupBoxFoto)
        self.cercaFotoBtn.setGeometry(QtCore.QRect(110, 50, 98, 27))
        self.cercaFotoBtn.setObjectName(_fromUtf8("cercaFotoBtn"))
        self.OpenBtn = QtGui.QPushButton(searchPhotoDialog)
        self.OpenBtn.setGeometry(QtCore.QRect(550, 590, 98, 27))
        self.OpenBtn.setObjectName(_fromUtf8("OpenBtn"))
        self.groupBox = QtGui.QGroupBox(searchPhotoDialog)
        self.groupBox.setGeometry(QtCore.QRect(350, 10, 331, 71))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.comboAlbums = QtGui.QComboBox(self.groupBox)
        self.comboAlbums.setGeometry(QtCore.QRect(20, 30, 221, 22))
        self.comboAlbums.setObjectName(_fromUtf8("comboAlbums"))
        self.eliminarBtn = QtGui.QPushButton(searchPhotoDialog)
        self.eliminarBtn.setGeometry(QtCore.QRect(760, 590, 93, 28))
        self.eliminarBtn.setObjectName(_fromUtf8("eliminarBtn"))
        self.editarBtn = QtGui.QPushButton(searchPhotoDialog)
        self.editarBtn.setGeometry(QtCore.QRect(660, 590, 93, 28))
        self.editarBtn.setObjectName(_fromUtf8("editarBtn"))
        self.labelTitol_2 = QtGui.QLabel(searchPhotoDialog)
        self.labelTitol_2.setGeometry(QtCore.QRect(20, 340, 53, 16))
        self.labelTitol_2.setObjectName(_fromUtf8("labelTitol_2"))
        self.lineTitol2 = QtGui.QLineEdit(searchPhotoDialog)
        self.lineTitol2.setGeometry(QtCore.QRect(60, 340, 261, 22))
        self.lineTitol2.setObjectName(_fromUtf8("lineTitol2"))
        self.labelFitxer = QtGui.QLabel(searchPhotoDialog)
        self.labelFitxer.setGeometry(QtCore.QRect(350, 340, 53, 16))
        self.labelFitxer.setObjectName(_fromUtf8("labelFitxer"))
        self.label = QtGui.QLabel(searchPhotoDialog)
        self.label.setGeometry(QtCore.QRect(400, 340, 451, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.listMetadataP = QtGui.QListWidget(searchPhotoDialog)
        self.listMetadataP.setGeometry(QtCore.QRect(20, 460, 141, 151))
        self.listMetadataP.setObjectName(_fromUtf8("listMetadataP"))
        self.listMetadataL = QtGui.QListWidget(searchPhotoDialog)
        self.listMetadataL.setGeometry(QtCore.QRect(200, 461, 151, 151))
        self.listMetadataL.setObjectName(_fromUtf8("listMetadataL"))
        self.listMetadataA = QtGui.QListWidget(searchPhotoDialog)
        self.listMetadataA.setGeometry(QtCore.QRect(380, 460, 141, 151))
        self.listMetadataA.setObjectName(_fromUtf8("listMetadataA"))
        self.radioPersona2 = QtGui.QRadioButton(searchPhotoDialog)
        self.radioPersona2.setGeometry(QtCore.QRect(20, 430, 95, 20))
        self.radioPersona2.setObjectName(_fromUtf8("radioPersona2"))
        self.radioLlocs2 = QtGui.QRadioButton(searchPhotoDialog)
        self.radioLlocs2.setGeometry(QtCore.QRect(200, 430, 95, 20))
        self.radioLlocs2.setObjectName(_fromUtf8("radioLlocs2"))
        self.radioAltres2 = QtGui.QRadioButton(searchPhotoDialog)
        self.radioAltres2.setGeometry(QtCore.QRect(380, 430, 95, 20))
        self.radioAltres2.setObjectName(_fromUtf8("radioAltres2"))
        self.labelMetadata2 = QtGui.QLabel(searchPhotoDialog)
        self.labelMetadata2.setGeometry(QtCore.QRect(20, 380, 61, 16))
        self.labelMetadata2.setObjectName(_fromUtf8("labelMetadata2"))
        self.lineMetadata2 = QtGui.QLineEdit(searchPhotoDialog)
        self.lineMetadata2.setGeometry(QtCore.QRect(80, 380, 241, 22))
        self.lineMetadata2.setObjectName(_fromUtf8("lineMetadata2"))
        self.addMetadataBtn = QtGui.QPushButton(searchPhotoDialog)
        self.addMetadataBtn.setGeometry(QtCore.QRect(330, 380, 93, 28))
        self.addMetadataBtn.setObjectName(_fromUtf8("addMetadataBtn"))
        self.delMetadataBtn = QtGui.QPushButton(searchPhotoDialog)
        self.delMetadataBtn.setGeometry(QtCore.QRect(430, 380, 93, 28))
        self.delMetadataBtn.setObjectName(_fromUtf8("delMetadataBtn"))

        self.retranslateUi(searchPhotoDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), searchPhotoDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), searchPhotoDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(searchPhotoDialog)

    def retranslateUi(self, searchPhotoDialog):
        searchPhotoDialog.setWindowTitle(_translate("searchPhotoDialog", "Cercador de Fotos", None))
        self.groupBoxCategory.setTitle(_translate("searchPhotoDialog", "Categoria", None))
        self.radioPersona.setText(_translate("searchPhotoDialog", "Persona", None))
        self.radioLloc.setText(_translate("searchPhotoDialog", "Lloc", None))
        self.radioButton.setText(_translate("searchPhotoDialog", "Altres", None))
        self.MetadataLabel.setText(_translate("searchPhotoDialog", "Metadata:", None))
        self.CercaMetadataBtn.setText(_translate("searchPhotoDialog", "Cerca", None))
        self.groupBoxFoto.setTitle(_translate("searchPhotoDialog", "Foto:", None))
        self.labelTitol.setText(_translate("searchPhotoDialog", "Titol:", None))
        self.cercaFotoBtn.setText(_translate("searchPhotoDialog", "Cerca", None))
        self.OpenBtn.setText(_translate("searchPhotoDialog", "Obre", None))
        self.groupBox.setTitle(_translate("searchPhotoDialog", "Albums", None))
        self.eliminarBtn.setText(_translate("searchPhotoDialog", "Eliminar", None))
        self.editarBtn.setText(_translate("searchPhotoDialog", "Desar", None))
        self.labelTitol_2.setText(_translate("searchPhotoDialog", "Titol", None))
        self.labelFitxer.setText(_translate("searchPhotoDialog", "Fitxer:", None))
        self.label.setText(_translate("searchPhotoDialog", "Direcció del Fitxer", None))
        self.radioPersona2.setText(_translate("searchPhotoDialog", "Persona", None))
        self.radioLlocs2.setText(_translate("searchPhotoDialog", "Llocs", None))
        self.radioAltres2.setText(_translate("searchPhotoDialog", "Altres", None))
        self.labelMetadata2.setText(_translate("searchPhotoDialog", "Metadata:", None))
        self.addMetadataBtn.setText(_translate("searchPhotoDialog", "Inserir", None))
        self.delMetadataBtn.setText(_translate("searchPhotoDialog", "Treure", None))

